# Generated by Django 3.2 on 2023-02-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230209_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='ethos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
