# Generated by Django 3.2 on 2023-02-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
