# Generated by Django 3.2 on 2023-02-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_ingredients_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients_list',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
    ]
