# Generated by Django 3.2 on 2023-02-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230210_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='line_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
