# Generated by Django 3.2 on 2023-02-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20230210_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='line_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
