# Generated by Django 3.2 on 2023-02-13 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20230213_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='line_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
